added location tile
simonyiszk/konf-web-2024 pull request #63
Opened 2024-03-01 17:26 UTC by FearsomeRover

I added the location tile, but noticed after, that the number of tiles is different on this dev branch, than it is on the main one. 12 or 13 organizers? If its 13, we need to modify the layout a little imo.

2024-03-01 21:17 UTC, Tschonti requested changes
There are 13 organisers, Beni is missing from staging for some reason. But I think the layout can stay, this wouldn't really fit in 2/3 of the screen.

Also, I found one edge case where the layout is messed up:
![image](https://github.com/simonyiszk/konf-web-2024/assets/13004605/bc134b7e-34be-4d31-a53b-0c9a49f04746)

Not a huge issue, if you can't solve it in a few minutes, you can leave it xd

2024-03-01 21:17 UTC, Tschonti commented on src/components/tiles/location-tile.tsx
> +    <Tile className='col-span-3 min-h-[500px]'>
This has to be `sm:col-span-2 lg:col-span-3` 
This is the class of the container: `grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3` So there is 1 column on base width, 2 on small, 3 above lg. If an item takes up more columns than there are, it messes up the other items

2024-03-02 10:12 UTC, Tschonti approved these changes
👌

2024-03-02 10:14 UTC, FearsomeRover commented
![image](https://github.com/simonyiszk/konf-web-2024/assets/22941324/23fc6d85-baa8-4bd7-a4dc-8bbdaa9920e3)

2024-03-02 10:18 UTC, merged