Feature/preserve site without api
simonyiszk/konf-web-2024 pull request #87
Opened 2024-04-13 10:40 UTC by Isti01

2024-04-13 14:29 UTC, berenteb requested changes

2024-04-13 14:29 UTC, berenteb commented on src/models/static/breaksData.ts
> +export const breaksData = [
Ide egy explicit típus jól jöhet, mert kimutatja ha véletlen beleírok valamit rosszul

2024-04-13 15:47 UTC, Isti01 commented on src/models/static/breaksData.ts
> +export const breaksData = [
Done

2024-04-13 18:37 UTC, berenteb approved these changes

2024-04-13 19:00 UTC, merged

2024-04-14 10:59 UTC, Tschonti reviewed
Thanks!

2024-04-14 10:59 UTC, Tschonti commented on src/app/actions.ts
> -  return data.success;
It would've been better if this was left here as a comment, could be a big help next year.
Also at the network functions